use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Project {
    pub id: String,
    pub name: String,
    pub goal: String,
    pub working_dir: String,
    pub state: String,
    pub overall: OverallStatus,
    pub phases: Vec<PhaseRuntime>,
    pub phase_count: u32,
    pub created_at: String,
    pub updated_at: String,
    /// Last message content emitted by 内阁 — used for context across dispatch cycles.
    #[serde(default)]
    pub last_neige_msg: String,
    /// Compact project summary updated as work progresses.
    #[serde(default)]
    pub summary: String,
    /// Project milestones (append-only, never trimmed), e.g.:
    /// [10:00] 整体方案审查通过
    /// [10:15] 皇帝批准整体方案
    #[serde(default)]
    pub task: String,
    /// Resume context: updated on every critical route so the project can
    /// be restored mid-execution. On load, the Cabinet sees this as
    /// 项目摘要 and knows what was happening.
    #[serde(default)]
    pub resume: String,
    /// Last summary report generated by 内阁 (summary skill output).
    /// Injected as context on subsequent summary calls for incremental updates.
    #[serde(default)]
    pub summary_prompt: String,
    /// Conversation log with smart retention:
    /// - Keeps last ~20 entries in full
    /// - Older entries are compressed into a summary line (derived from task milestones)
    /// Format: [摘要行]\n[近期详细条目...]
    #[serde(default)]
    pub talk: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProjectSummary {
    pub id: String,
    pub name: String,
    pub goal: String,
    pub working_dir: String,
    pub created_at: String,
    pub overall_status: String,
    pub phases_status: String,
}

/// Snapshot of project progress for the frontend dashboard.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProjectSnapshot {
    pub overall: OverallStatus,
    pub phases: Vec<PhaseSnapshot>,
    pub overall_progress: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PhaseSnapshot {
    pub index: u32,
    pub design: String,
    pub execution: String,
}

impl Project {
    /// Append a line to the talk log. When over capacity, oldest entries
    /// are compressed into a summary line derived from task milestones.
    pub fn append_talk(&mut self, line: &str) {
        let ts = chrono::Local::now().format("%H:%M").to_string();
        let entry = format!("[{}] {}", ts, line);
        if self.talk.is_empty() {
            self.talk = entry;
        } else {
            self.talk.push_str(&format!("\n{}", entry));
        }
        // Aggressive trim: keep only recent entries to control context growth
        let lines: Vec<&str> = self.talk.lines().collect();
        if lines.len() > 12 {
            let summary = if self.task.is_empty() {
                "项目进行中"
            } else {
                let last = self.task.lines().last().unwrap_or("项目进行中");
                last.trim_start_matches(|c: char| c == '[' || c == ']' || c.is_numeric() || c == ':' || c == ' ')
            };
            let kept = lines[lines.len().saturating_sub(8)..].join("\n");
            self.talk = format!("【前期概要】{}\n---\n{}", summary, kept);
        }
    }

    /// Append a milestone to the project task log (never trimmed).

    /// Build a progress snapshot for the frontend.
    pub fn snapshot(&self) -> ProjectSnapshot {
        ProjectSnapshot {
            overall: self.overall.clone(),
            phases: self.phases.iter().map(|p| PhaseSnapshot {
                index: p.index,
                design: p.design.label(p.index),
                execution: p.execution.label(p.index),
            }).collect(),
            overall_progress: calc_progress(self.phase_count, &self.overall, &self.phases),
        }
    }
}

fn calc_progress(phase_count: u32, overall: &OverallStatus, phases: &[PhaseRuntime]) -> f64 {
    let total = phase_count as f64 * 2.0 + 1.0;
    let mut done = 0.0;
    if *overall == OverallStatus::Approved { done += 1.0; }
    for phase in phases {
        if phase.design == PhaseDesignStatus::Approved { done += 1.0; }
        if phase.execution == PhaseExecutionStatus::Completed { done += 1.0; }
    }
    done / total * 100.0
}

// ── Project state enums ──

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum OverallStatus {
    NotStarted,
    Designing,
    Reviewing,
    PendingApproval,
    Rejected,
    Approved,
}

impl OverallStatus {
    pub fn label(&self) -> &str {
        match self {
            OverallStatus::NotStarted => "整体方案：未开始",
            OverallStatus::Designing => "整体方案：设计中",
            OverallStatus::Reviewing => "整体方案：审查中",
            OverallStatus::PendingApproval => "整体方案：待皇帝审批",
            OverallStatus::Rejected => "整体方案：审查发现问题",
            OverallStatus::Approved => "整体方案：已批准",
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PhaseRuntime {
    pub index: u32,
    pub design: PhaseDesignStatus,
    pub execution: PhaseExecutionStatus,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum PhaseDesignStatus {
    NotStarted,
    Designing,
    Reviewing,
    PendingApproval,
    Rejected,
    Approved,
}

impl PhaseDesignStatus {
    pub fn label(&self, phase: u32) -> String {
        match self {
            PhaseDesignStatus::NotStarted => format!("阶段{}设计：未开始", phase),
            PhaseDesignStatus::Designing => format!("阶段{}设计：设计中", phase),
            PhaseDesignStatus::Reviewing => format!("阶段{}设计：审查中", phase),
            PhaseDesignStatus::PendingApproval => format!("阶段{}设计：待皇帝审批", phase),
            PhaseDesignStatus::Rejected => format!("阶段{}设计：审查发现问题", phase),
            PhaseDesignStatus::Approved => format!("阶段{}设计：已批准", phase),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum PhaseExecutionStatus {
    NotStarted,
    TaskBreakdown,
    Testing,
    Implementing,
    Checking,
    Standards,
    Logging,
    Blocked { reason: String },
    MinorIssue,
    Completed,
}

impl PhaseExecutionStatus {
    pub fn label(&self, phase: u32) -> String {
        match self {
            PhaseExecutionStatus::NotStarted => format!("阶段{}执行：未开始", phase),
            PhaseExecutionStatus::TaskBreakdown => format!("阶段{}执行：吏部拆解任务", phase),
            PhaseExecutionStatus::Testing => format!("阶段{}执行：兵部测试", phase),
            PhaseExecutionStatus::Implementing => format!("阶段{}执行：工部编码", phase),
            PhaseExecutionStatus::Checking => format!("阶段{}执行：刑部检查", phase),
            PhaseExecutionStatus::Standards => format!("阶段{}执行：礼部检查", phase),
            PhaseExecutionStatus::Logging => format!("阶段{}执行：户部记录", phase),
            PhaseExecutionStatus::Blocked { .. } => format!("阶段{}执行：阻塞", phase),
            PhaseExecutionStatus::MinorIssue => format!("阶段{}执行：轻微问题", phase),
            PhaseExecutionStatus::Completed => format!("阶段{}执行：已完成", phase),
        }
    }
}
