use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Project {
    pub id: String,
    pub name: String,
    pub goal: String,
    pub working_dir: String,
    pub state: String,
    pub overall: OverallStatus,
    pub phases: Vec<PhaseRuntime>,
    pub phase_count: u32,
    pub created_at: String,
    pub updated_at: String,
    /// Last message content emitted by 内阁 — used for context across dispatch cycles.
    #[serde(default)]
    pub last_neige_msg: String,
    /// Compact project summary updated as work progresses.
    #[serde(default)]
    pub summary: String,
    /// Project milestones (append-only, never trimmed), e.g.:
    /// [10:00] 整体方案审查通过
    /// [10:15] 皇帝批准整体方案
    #[serde(default)]
    pub task: String,
    /// Resume context: updated on every critical route so the project can
    /// be restored mid-execution. On load, the Cabinet sees this as
    /// 项目摘要 and knows what was happening.
    #[serde(default)]
    pub resume: String,
    /// Last summary report generated by 内阁 (summary skill output).
    /// Injected as context on subsequent summary calls for incremental updates.
    #[serde(default)]
    pub summary_prompt: String,
    /// Conversation log with smart retention:
    /// - Keeps last ~20 entries in full
    /// - Older entries are compressed into a summary line (derived from task milestones)
    ///   Format: `[摘要行]\n[近期详细条目...]`
    #[serde(default)]
    pub talk: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProjectSummary {
    pub id: String,
    pub name: String,
    pub goal: String,
    pub working_dir: String,
    pub created_at: String,
    pub overall_status: String,
    pub phases_status: String,
}

/// Snapshot of project progress for the frontend dashboard.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProjectSnapshot {
    pub overall: OverallStatus,
    pub phases: Vec<PhaseSnapshot>,
    pub overall_progress: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PhaseSnapshot {
    pub index: u32,
    pub design: String,
    pub execution: String,
}

impl Project {
    /// Append a line to the talk log. When over capacity, oldest entries
    /// are compressed into a summary line derived from task milestones.
    pub fn append_talk(&mut self, line: &str) {
        let ts = chrono::Local::now().format("%H:%M").to_string();
        let entry = format!("[{}] {}", ts, line);
        if self.talk.is_empty() {
            self.talk = entry;
        } else {
            self.talk.push_str(&format!("\n{}", entry));
        }
        // Aggressive trim: keep only recent entries to control context growth
        let lines: Vec<&str> = self.talk.lines().collect();
        if lines.len() > 12 {
            let summary = if self.task.is_empty() {
                "Project in progress"
            } else {
                let last = self.task.lines().last().unwrap_or("项目进行中");
                last.trim_start_matches(|c: char| {
                    c == '[' || c == ']' || c.is_numeric() || c == ':' || c == ' '
                })
            };
            let kept = lines[lines.len().saturating_sub(8)..].join("\n");
            self.talk = format!("[Previous Summary] {}\n---\n{}", summary, kept);
        }
    }

    /// Append a milestone to the project task log (never trimmed).
    /// Build a progress snapshot for the frontend.
    pub fn snapshot(&self) -> ProjectSnapshot {
        ProjectSnapshot {
            overall: self.overall.clone(),
            phases: self
                .phases
                .iter()
                .map(|p| PhaseSnapshot {
                    index: p.index,
                    design: p.design.label(p.index),
                    execution: p.execution.label(p.index),
                })
                .collect(),
            overall_progress: calc_progress(self.phase_count, &self.overall, &self.phases),
        }
    }
}

fn calc_progress(phase_count: u32, overall: &OverallStatus, phases: &[PhaseRuntime]) -> f64 {
    let total = phase_count as f64 * 2.0 + 1.0;
    let mut done = 0.0;
    if *overall == OverallStatus::Approved {
        done += 1.0;
    }
    for phase in phases {
        if phase.design == PhaseDesignStatus::Approved {
            done += 1.0;
        }
        if phase.execution == PhaseExecutionStatus::Completed {
            done += 1.0;
        }
    }
    done / total * 100.0
}

// ── Project state enums ──

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum OverallStatus {
    NotStarted,
    Designing,
    Reviewing,
    PendingApproval,
    Rejected,
    Approved,
}

impl OverallStatus {
    pub fn label(&self) -> &str {
        match self {
            OverallStatus::NotStarted => "Overall: Not Started",
            OverallStatus::Designing => "Overall: Designing",
            OverallStatus::Reviewing => "Overall: Reviewing",
            OverallStatus::PendingApproval => "Overall: Pending Emperor Approval",
            OverallStatus::Rejected => "Overall: Issues Found in Review",
            OverallStatus::Approved => "Overall: Approved",
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PhaseRuntime {
    pub index: u32,
    pub design: PhaseDesignStatus,
    pub execution: PhaseExecutionStatus,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum PhaseDesignStatus {
    NotStarted,
    Designing,
    Reviewing,
    PendingApproval,
    Rejected,
    Approved,
}

impl PhaseDesignStatus {
    pub fn label(&self, phase: u32) -> String {
        match self {
            PhaseDesignStatus::NotStarted => format!("Phase {} Design: Not Started", phase),
            PhaseDesignStatus::Designing => format!("Phase {} Design: Designing", phase),
            PhaseDesignStatus::Reviewing => format!("Phase {} Design: Reviewing", phase),
            PhaseDesignStatus::PendingApproval => {
                format!("Phase {} Design: Pending Emperor Approval", phase)
            }
            PhaseDesignStatus::Rejected => {
                format!("Phase {} Design: Issues Found in Review", phase)
            }
            PhaseDesignStatus::Approved => format!("Phase {} Design: Approved", phase),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum PhaseExecutionStatus {
    NotStarted,
    TaskBreakdown,
    Testing,
    Implementing,
    Checking,
    Standards,
    Logging,
    Blocked { reason: String },
    MinorIssue,
    Completed,
}

impl PhaseExecutionStatus {
    pub fn label(&self, phase: u32) -> String {
        match self {
            PhaseExecutionStatus::NotStarted => format!("Phase {} Execution: Not Started", phase),
            PhaseExecutionStatus::TaskBreakdown => {
                format!("Phase {} Execution: Task Breakdown", phase)
            }
            PhaseExecutionStatus::Testing => format!("Phase {} Execution: Testing", phase),
            PhaseExecutionStatus::Implementing => format!("Phase {} Execution: Coding", phase),
            PhaseExecutionStatus::Checking => format!("Phase {} Execution: Checking", phase),
            PhaseExecutionStatus::Standards => {
                format!("Phase {} Execution: Standards Check", phase)
            }
            PhaseExecutionStatus::Logging => format!("Phase {} Execution: Logging", phase),
            PhaseExecutionStatus::Blocked { .. } => format!("Phase {} Execution: Blocked", phase),
            PhaseExecutionStatus::MinorIssue => format!("Phase {} Execution: Minor Issue", phase),
            PhaseExecutionStatus::Completed => format!("Phase {} Execution: Completed", phase),
        }
    }
}
